version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - scripts/install_dependencies.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
    - appspec.yml
    - target/contacts-app.jar
  discard-paths: yes
