version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - appspec.yml
    - target/contacts-app.jar
    - scripts/*.sh
  discard-paths: yes
